<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <title>Liste de tâches</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background: #f4f4f4;
      display: flex;
      justify-content: center;
      align-items: flex-start;
      padding: 40px;
    }
    .todo-container {
      background: white;
      padding: 20px;
      border-radius: 12px;
      box-shadow: 0 4px 10px rgba(0,0,0,0.1);
      width: 350px;
    }
    h2 {
      text-align: center;
      margin-bottom: 15px;
    }
    .input-container {
      display: flex;
      margin-bottom: 15px;
    }
    .input-container input {
      flex: 1;
      padding: 8px;
      border: 1px solid #ddd;
      border-radius: 8px;
    }
    .input-container button {
      margin-left: 8px;
      padding: 8px 12px;
      border: none;
      background: #4caf50;
      color: white;
      border-radius: 8px;
      cursor: pointer;
    }
    .input-container button:hover {
      background: #45a049;
    }
    ul {
      list-style-type: none;
      padding: 0;
    }
    li {
      background: #fafafa;
      padding: 10px;
      margin-bottom: 8px;
      border-radius: 8px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    li.completed {
      text-decoration: line-through;
      color: gray;
    }
    .delete-btn {
      background: red;
      color: white;
      border: none;
      padding: 5px 8px;
      border-radius: 6px;
      cursor: pointer;
    }
    .delete-btn:hover {
      background: darkred;
    }
  </style>
</head>
<body>
  <div class="todo-container">
    <h2>📝 Ma liste de tâches</h2>
    <div class="input-container">
      <input type="text" id="taskInput" placeholder="Ajouter une tâche...">
      <button onclick="addTask()">Ajouter</button>
    </div>
    <ul id="taskList"></ul>
  </div>

  <script>
    function addTask() {
      const input = document.getElementById("taskInput");
      const taskText = input.value.trim();
      if (taskText === "") return;

      const li = document.createElement("li");
      li.innerHTML = `
        <span onclick="toggleTask(this)">${taskText}</span>
        <button class="delete-btn" onclick="deleteTask(this)">X</button>
      `;
      document.getElementById("taskList").appendChild(li);
      input.value = "";
    }

    function toggleTask(element) {
      element.parentElement.classList.toggle("completed");
    }

    function deleteTask(button) {
      button.parentElement.remove();
    }
  </script>
</body>
</html>
